### ISSUE TITLE
Administrator roles should see tree view

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#641]
Users with administrator or atlas administrator roles should automatically have the Nunaliit advanced user functionality applied (such as seeing the tree view button.)

**Comment by boikle** [comment]
One simple solution for this problem is to update the following css rule, 

from:

```css
.nunaliit_user_advanced .nunaliit_form_link_tree_view {
	display:-moz-inline-stack;
	display:inline-block;
}
```
to 

```css
.nunaliit_user_administrator .nunaliit_form_link_tree_view {
	display:-moz-inline-stack;
	display:inline-block;
}
```
This should result in the treeview button being displayed for all admins. 

Would this be an acceptable solution?

**Comment by ahayes** [comment]
Except that would break existing functionality for non-admin advanced users. But I suspect it could be made to work for both.

**Comment by boikle** [comment]
Ok. The following should be sufficient for allowing both to see the tree view button, without making any changes to the _users db in couchDb: 

```css
.nunaliit_user_administrator .nunaliit_form_link_tree_view,
.nunaliit_user_advanced .nunaliit_form_link_tree_view  {
	display:-moz-inline-stack;
	display:inline-block;
}
```
